name: API Keep Alive

on:
  schedule:
    - cron: '*/10 * * * *'   # Executa a cada 10 minutos
  workflow_dispatch:         # Permite rodar manualmente para testar

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API
        run: |
          if curl -s --fail https://nd-lanches-api.onrender.com/api/loja/nd-lanches/status; then
            echo "✅ Ping realizado com sucesso às $(date)"
          else
            echo "❌ Falha no ping às $(date)"
            exit 1
          fi